### ISSUE TITLE
Printable cards don't have creature subtypes

### ISSUE THREAD

**Issue by eternaldensity** [croxis/mtgai#2]
For example, the generated card

```
|avalan faceraker||creature||goblin shaman|N|&^^/&^^|{^^BB}|rat an additional cost step for all artifacts.|
```

Shows up as

![image](https://cloud.githubusercontent.com/assets/5440153/9078212/ec341d2c-3b7d-11e5-894c-64f428ed18d0.png)

(I'm going to interpret this card as 'all artifacts have 'Cumulative Upkeep: Sacrifice a Rat')

**Comment by croxis** [comment]
Fixed
